version: '3.9'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=donation_platform
    image: postgres:latest
    networks:
      - donation_platform_network

  app:
    container_name: movie
    image: ivanovvadim/donation_platform:v2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - donation_platform_network

networks:
  donation_platform_network:
    driver: bridge